package com.gapmesh.droid.onboarding

enum class OnboardingState {
    LANGUAGE_SELECTION,
    CHECKING,
    BLUETOOTH_CHECK,
    LOCATION_CHECK,
    BATTERY_OPTIMIZATION_CHECK,
    PERMISSION_EXPLANATION,
    BACKGROUND_LOCATION_EXPLANATION,
    PERMISSION_REQUESTING,
    INITIALIZING,
    TUTORIAL,
    COMPLETE,
    ERROR
}

